# Generated by Django 2.1.5 on 2019-01-08 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grapher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JasonParser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('jason', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='JasonParserAlias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('path', models.CharField(max_length=200)),
                ('jasonParser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grapher.JasonParser')),
            ],
        ),
    ]
