# Generated by Django 2.1.5 on 2019-01-20 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grapher', '0003_auto_20190117_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='logparser',
            name='totalPattern',
            field=models.IntegerField(null=True),
        ),
    ]
