# Generated by Django 2.1.5 on 2019-01-24 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grapherEntities', '0001_initial'),
        ('grapher', '0004_logparser_totalpattern'),
    ]

    operations = [
        migrations.AddField(
            model_name='logparser',
            name='grapherEntity',
            field=models.ManyToManyField(to='grapherEntities.GrapherEntity'),
        ),
        migrations.AlterField(
            model_name='logparsercrudformcustompattern',
            name='customPatternName',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='logparsercrudformstaticpattern',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
