# Generated by Django 2.1.5 on 2019-01-24 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grapher', '0005_auto_20190124_1217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logparser',
            name='grapherEntity',
        ),
    ]
