# Generated by Django 2.1.5 on 2019-01-24 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grapherEntities', '0001_initial'),
        ('grapher', '0006_remove_logparser_grapherentity'),
    ]

    operations = [
        migrations.AddField(
            model_name='logparser',
            name='grapherEntity',
            field=models.ManyToManyField(to='grapherEntities.GrapherEntity'),
        ),
    ]
