# Generated by Django 2.1.5 on 2019-01-28 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grapher', '0007_logparser_grapherentity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logparser',
            name='grapherEntity',
            field=models.ManyToManyField(blank=True, related_name='logParsers_list', to='grapherEntities.GrapherEntity'),
        ),
    ]
