# Generated by Django 2.1.5 on 2019-01-31 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grapher', '0012_logparser_grapherentity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logparser',
            name='grapherEntity',
        ),
    ]
