# Generated by Django 2.1.5 on 2019-01-31 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grapher', '0011_remove_logparser_grapherentity'),
        ('grapherEntities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grapherentity',
            name='logParser_list',
            field=models.ManyToManyField(blank=True, related_name='logParsers_list', to='grapher.LogParser'),
        ),
    ]
