# Generated by Django 2.1.5 on 2019-01-31 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grapherEntities', '0002_grapherentity_logparser_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grapherentity',
            name='logParser_list',
        ),
    ]
