# Generated by Django 2.1.5 on 2019-03-01 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grapherEntities', '0006_grapherentity_jasondata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grapherentity',
            name='jasonData',
            field=models.TextField(),
        ),
    ]
